spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        show_sql: true
#        format_sql: true
        ddl-auto: validate
  flyway:
    schemas: public

logging:
  file:
    name: vegera.log